version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "zoverflow-image"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pdkg3kh8h6d8"
s3_prefix = "zoverflow-image"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
